set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN H5 [get_ports y3]
set_property PACKAGE_PIN J5 [get_ports y2]
set_property PACKAGE_PIN T9 [get_ports y1]
set_property PACKAGE_PIN T10 [get_ports y0]
set_property PACKAGE_PIN R10 [get_ports data]
set_property IOSTANDARD LVCMOS33 [get_ports data]
set_property IOSTANDARD LVCMOS33 [get_ports y0]
set_property IOSTANDARD LVCMOS33 [get_ports y1]
set_property IOSTANDARD LVCMOS33 [get_ports y2]
set_property IOSTANDARD LVCMOS33 [get_ports y3]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
